### ISSUE TITLE
Offline Approval Link - 404

### ISSUE THREAD

**Issue by DaveGill82** [nathanwoulfe/Plumber-2#25]
Hi Nathan, I’m evaluating Plumber on my local machine, I’ve configured the Site URL and Edit Site URL and set a group to allow offline approval. I receive an email but the offline approval link returns a 404, am I missing something?

Thanks,

Dave

**Comment by nathanwoulfe** [comment]
Hi Dave - re the email I sent earlier, v1.3.4 should resolve these issues. Interested in how you fare with the offline approval, particularly if you're on Umbraco Cloud (seems to work fine locally/on-prem, but having token issues on Cloud, still working on it...)

**Comment by DaveGill82** [comment]
Hi Nathan, 

I've upgraded to v1.3.4 and the offline approval link is working. I'm still having a few issues, i've listed the steps below, hope it helps. I'm not using Umbraco Cloud, we host it.

1. Logon on to Umbraco as Editor & make change (request approval) then Log Off
2. Click 'Offline Approval' Link in Email
3. Page Loads in Preview Mode
4. Click the 'Action Workflow' button
5. I get the error below in browser console

![image](https://user-images.githubusercontent.com/5846160/85505573-86fc2b00-b5e6-11ea-9658-668cd218e110.png)

6. Navigate to admin area (still in preview mode), I've automatically been logged in as the offline approver
7. Follow the 'Offline Approval' Link again from the email
8. Click 'Action Workflow' and the approval screen now opens
9. Click Approve
13. The change is approved in the workflow but i get the error:: "INVALID REQUEST: The requested URL does not map to a valid workflow process. The task may have already been completed, or the requesting user does not have permission to action the task."

There seems to be two issues the first when trying to approve a change without navigating to the admin area, I'm currently running everything locally, could this be causing the issue? The second is the invalid request error i get despite the workflow being approved. I have got two stages in the workflow, not sure if this makes a difference.

Let me know if you need more info.

Thanks,

Dave

**Comment by nathanwoulfe** [comment]
That's actually a good result - it's the same error as I'm seeing on Cloud (the 417 invalid token), so at least it's consistent. Definitely sounds like the authentication bastardisation wasn't working correctly all the time, so fixing it should fix it everywhere.

I've pushed more changes to rewrite the old authentication approach, it's all working fine locally (not that that means much, given the previous one was too 🤷). That's all in the pending nightly which will be on NuGet as a pre-release around 90 minutes from now.

When you get the Invalid Request error, where is that displayed - as an overlay, or in the console? If it's the former, it will be related to the 417 error, as Plumber won't be able to check the workflow status without the correct token set.

**Comment by DaveGill82** [comment]
Cheers Nathan, I'll check the new version, the invalid request error appears as an overlay.

**Comment by nathanwoulfe** [comment]
Good to hear - it's definitely all related. Offline approval is trying to make Umbraco do things it was never suppose to do, hence these issues. I'm still confident it can be made to work, especially since it's ok when I run locally...

**Comment by DaveGill82** [comment]
I just tried the beta version, when i click 'Action Workflow' i get a msg...

"Current user does not have permission to action the workflow."

When i browse to the admin tool the offline approver has been logged in and can approve the change from there.

**Comment by nathanwoulfe** [comment]
You're not the only one seeing that exact behaviour. At least the login/auth is working correctly, else you'd not see anything in the overlay. I'll keep digging.

**Comment by nathanwoulfe** [comment]
@DaveGill82 found the problem - running Umbraco in release mode reproduces the issue. Not sure why, but I can see what needs fixing. Will have it in a nightly tonight/tomorrow.

**Comment by DaveGill82** [comment]
@nathanwoulfe did you roll out a fix? i've test 1.3.5-beta-000390 and I'm getting the 417 error again when I log off after making the initial change.

**Comment by nathanwoulfe** [comment]
When you log off as in out of the backoffice? Not after touching the offline approval view?

You're running the latest beta, where I thought everything was working correctly... Will have another look today

**Comment by nathanwoulfe** [comment]
Hi @DaveGill82 I've had another dig into this, seems something changed in v8.5.5, related to a security issue in Client Dependency Framework. While I don't see an obvious link between that and the issue here, I can verify that the offline approval fails on 8.5.5, but works on earlier versions.

Tonight's beta/nightly has a further update to remove some Umbraco dependencies, which I've verified on 8.5.5, in release mode, and works fine. Hopefully same for you...

**Comment by nathanwoulfe** [comment]
I'm confident (famous last words) this is working on v.1.3.5, which is building now.

**Comment by lhall690** [comment]
Hi Nathan, just wanted to check this feature is working in the latest release? Just working out whether to recommend or not, as I had some issues I was never ever to resolve with Plumber 1 in offline approval. Cheers

**Comment by nathanwoulfe** [comment]
@lhall690 as far as I'm aware it's working... Released these changes a few patches ago and haven't heard anything to indicate that it's not working. 

It's potentially always going to be fragile, because it probably shouldn't work - although the last changes did simplify the identify stuff quite a bit, so it's perhaps more robust now. 

So long story short, it's working, as far as I'm aware 😁

**Comment by lhall690** [comment]
Great! Glad to hear it :)
