### ISSUE TITLE
Error on requesting publish

### ISSUE THREAD

**Issue by garethf89** [nathanwoulfe/Plumber-2#3]
The below error occurs when I click 'request Publish',  this is when I am using an 'Exlcude workflow'.

{"@t":"2019-09-26T16:16:13.2863092Z","@mt":"Error getting node config","@l":"Error","SourceContext":"Plumber.Web.Api.ConfigController","ProcessId":2104,"ProcessName":"iisexpress","ThreadId":28,"AppDomainId":4,"AppDomainAppId":"XXX","MachineName":"XXX","Log4NetLevel":"ERROR","HttpRequestNumber":10,"HttpRequestId":"fbb298ab-7892-4e6b-90ff-5e1328ff8504"}

![Screenshot 2019-10-07 at 16 17 46](https://user-images.githubusercontent.com/5473451/66325306-eca46c00-e91e-11e9-9b35-ab3225668257.png)

**Comment by nathanwoulfe** [comment]
Those log messages are pathetic, I need to fix them...

Will have a look into it, I don't think the workflow type will be a factor, something's not happy when checking the config for the current node, I'm guessing it's variant-related.

**Comment by nathanwoulfe** [comment]
Could you also share the full stack trace? Might need to grab it from the log file directly

**Comment by garethf89** [comment]
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteScalar() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 334
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteScalar>b__32_0() in d:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 214
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0() in d:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 222
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in d:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f) in d:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 219
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteScalar() in d:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 214
   at NPoco.Database.ExecuteScalarHelper(DbCommand cmd)
   at NPoco.DatabaseTypes.SqlServerDatabaseType.ExecuteInsert[T](Database db, DbCommand cmd, String primaryKeyName, Boolean useOutputClause, T poco, Object[] args)
   at NPoco.Database.InsertImp[T](PocoData pocoData, String tableName, String primaryKeyName, Boolean autoIncrement, T poco)
   at NPoco.Database.Insert[T](String tableName, String primaryKeyName, Boolean autoIncrement, T poco)
   at NPoco.Database.Insert[T](T poco)
   at Plumber.Core.Repositories.Implement.Database.Insert[T](Object model)
   at Plumber.Core.Repositories.Implement.BaseWorkflowRepository`1.Insert(TEntity entity)
   at Plumber.Core.Services.Implement.InstancesService.Insert(WorkflowInstancePoco instance)
   at Plumber.Core.Processes.WorkflowProcess.InitiateWorkflow(Int32 nodeId, Int32 contentTypeId, Int32 authorUserId, String authorComment, String variant)
   at Plumber.Web.Api.ActionsController.InitiateWorkflow(InitiateWorkflowModel model)

**Comment by nathanwoulfe** [comment]
Nothing overly useful there. Try updating to the latest beta, I fixed a couple of potentially dodgy bits which may have resolved it. 

I haven't been able to replicate the error, does it happen every attempt?

**Comment by garethf89** [comment]
Thanks for looking at that.

I deleted my Approval Group and created a new one, it worked. Not sure why but at least its fixed.

Im having a couple of usability issues still:

1. Every screen its coming up with a pop-up to go to the purchase screen and trial option is greyed out. I just need basic workflow working for a new website my company are building so trial is fine, however i cant select it and it keeps popping up.

2. I am trying to attach a to my master node and it wont let me, it says 'Save successful' in green and it is gone when  I refresh. If i try to navigate I just get 'Discard changes?' dialog no matter how many times I click save.

**Comment by garethf89** [comment]
Hi @nathanwoulfe ,

Thanks for all the help with issues so far and I really do appreciate the effort you have put in with this plugin.

I am at a point in my project where I have to make a final decision on Umbraco 7 vs 8. I really don't want to start using the old version as 8 has so many good features. However Plumber is critical functionality for the business.  

Do you know when this Plugin might be usable on 8? If it is going to be a while that's fine I just need to communicate to business and the other devs.

**Comment by nathanwoulfe** [comment]
Hi @garethf89 no worries, I appreciate the feedback - helped me to track down a few bits that I'd made silly assumptions around.

I've sorted the two issues you raised earlier, need to package that up and release the new beta, which I'll get done tomorrow.

After that, I'd like to do some full end-to-end user testing on a clean install, to hopefully (or hopefully not) throw up any other oddities, but all going well there, I'd like to have an initial release in a couple of weeks, or end of November at the latest. Ballpark of course, other work (paid stuff) has to take priority...
